const STATE_BY_PREFIX: Array<{ prefix: string; state: string }> = [
  { prefix: '004', state: 'NY' },
  { prefix: '005', state: 'NY' },
  { prefix: '006', state: 'PR' },
  { prefix: '007', state: 'PR' },
  { prefix: '009', state: 'PR' },
  { prefix: '008', state: 'VI' },
  { prefix: '010', state: 'MA' },
  { prefix: '011', state: 'MA' },
  { prefix: '012', state: 'MA' },
  { prefix: '013', state: 'MA' },
  { prefix: '014', state: 'MA' },
  { prefix: '015', state: 'MA' },
  { prefix: '016', state: 'MA' },
  { prefix: '017', state: 'MA' },
  { prefix: '018', state: 'MA' },
  { prefix: '019', state: 'MA' },
  { prefix: '020', state: 'MA' },
  { prefix: '021', state: 'MA' },
  { prefix: '022', state: 'MA' },
  { prefix: '023', state: 'MA' },
  { prefix: '024', state: 'MA' },
  { prefix: '025', state: 'MA' },
  { prefix: '026', state: 'MA' },
  { prefix: '027', state: 'MA' },
  { prefix: '028', state: 'RI' },
  { prefix: '029', state: 'RI' },
  { prefix: '030', state: 'NH' },
  { prefix: '031', state: 'NH' },
  { prefix: '032', state: 'NH' },
  { prefix: '033', state: 'NH' },
  { prefix: '034', state: 'NH' },
  { prefix: '035', state: 'NH' },
  { prefix: '036', state: 'NH' },
  { prefix: '037', state: 'NH' },
  { prefix: '038', state: 'NH' },
  { prefix: '039', state: 'ME' },
  { prefix: '040', state: 'ME' },
  { prefix: '041', state: 'ME' },
  { prefix: '042', state: 'ME' },
  { prefix: '043', state: 'ME' },
  { prefix: '044', state: 'ME' },
  { prefix: '045', state: 'ME' },
  { prefix: '046', state: 'ME' },
  { prefix: '047', state: 'ME' },
  { prefix: '048', state: 'ME' },
  { prefix: '049', state: 'ME' },
  { prefix: '05', state: 'VT' },
  { prefix: '06', state: 'CT' },
  { prefix: '070', state: 'NJ' },
  { prefix: '071', state: 'NJ' },
  { prefix: '072', state: 'NJ' },
  { prefix: '073', state: 'NJ' },
  { prefix: '074', state: 'NJ' },
  { prefix: '075', state: 'NJ' },
  { prefix: '076', state: 'NJ' },
  { prefix: '077', state: 'NJ' },
  { prefix: '078', state: 'NJ' },
  { prefix: '079', state: 'NJ' },
  { prefix: '08', state: 'NJ' },
  { prefix: '09', state: 'AE' },
  { prefix: '10', state: 'NY' },
  { prefix: '11', state: 'NY' },
  { prefix: '12', state: 'NY' },
  { prefix: '13', state: 'NY' },
  { prefix: '14', state: 'NY' },
  { prefix: '15', state: 'PA' },
  { prefix: '16', state: 'PA' },
  { prefix: '17', state: 'PA' },
  { prefix: '18', state: 'PA' },
  { prefix: '19', state: 'PA' },
  { prefix: '20', state: 'DC' },
  { prefix: '21', state: 'MD' },
  { prefix: '22', state: 'VA' },
  { prefix: '23', state: 'VA' },
  { prefix: '24', state: 'VA' },
  { prefix: '247', state: 'WV' },
  { prefix: '248', state: 'WV' },
  { prefix: '249', state: 'WV' },
  { prefix: '25', state: 'WV' },
  { prefix: '26', state: 'WV' },
  { prefix: '27', state: 'NC' },
  { prefix: '28', state: 'NC' },
  { prefix: '29', state: 'SC' },
  { prefix: '30', state: 'GA' },
  { prefix: '31', state: 'GA' },
  { prefix: '398', state: 'GA' },
  { prefix: '399', state: 'GA' },
  { prefix: '32', state: 'FL' },
  { prefix: '33', state: 'FL' },
  { prefix: '34', state: 'FL' },
  { prefix: '35', state: 'AL' },
  { prefix: '36', state: 'AL' },
  { prefix: '37', state: 'TN' },
  { prefix: '38', state: 'TN' },
  { prefix: '386', state: 'MS' },
  { prefix: '387', state: 'MS' },
  { prefix: '388', state: 'MS' },
  { prefix: '389', state: 'MS' },
  { prefix: '39', state: 'MS' },
  { prefix: '40', state: 'KY' },
  { prefix: '41', state: 'KY' },
  { prefix: '42', state: 'KY' },
  { prefix: '43', state: 'OH' },
  { prefix: '44', state: 'OH' },
  { prefix: '45', state: 'OH' },
  { prefix: '46', state: 'IN' },
  { prefix: '47', state: 'IN' },
  { prefix: '48', state: 'MI' },
  { prefix: '49', state: 'MI' },
  { prefix: '50', state: 'IA' },
  { prefix: '51', state: 'IA' },
  { prefix: '52', state: 'IA' },
  { prefix: '53', state: 'WI' },
  { prefix: '54', state: 'WI' },
  { prefix: '55', state: 'MN' },
  { prefix: '56', state: 'MN' },
  { prefix: '57', state: 'SD' },
  { prefix: '58', state: 'ND' },
  { prefix: '59', state: 'MT' },
  { prefix: '60', state: 'IL' },
  { prefix: '61', state: 'IL' },
  { prefix: '62', state: 'IL' },
  { prefix: '63', state: 'MO' },
  { prefix: '64', state: 'MO' },
  { prefix: '65', state: 'MO' },
  { prefix: '66', state: 'KS' },
  { prefix: '67', state: 'KS' },
  { prefix: '68', state: 'NE' },
  { prefix: '69', state: 'NE' },
  { prefix: '70', state: 'LA' },
  { prefix: '71', state: 'LA' },
  { prefix: '72', state: 'AR' },
  { prefix: '716', state: 'AR' },
  { prefix: '73', state: 'OK' },
  { prefix: '74', state: 'OK' },
  { prefix: '75', state: 'TX' },
  { prefix: '76', state: 'TX' },
  { prefix: '77', state: 'TX' },
  { prefix: '78', state: 'TX' },
  { prefix: '79', state: 'TX' },
  { prefix: '80', state: 'CO' },
  { prefix: '81', state: 'CO' },
  { prefix: '82', state: 'WY' },
  { prefix: '83', state: 'WY' },
  { prefix: '832', state: 'ID' },
  { prefix: '833', state: 'ID' },
  { prefix: '834', state: 'ID' },
  { prefix: '835', state: 'ID' },
  { prefix: '836', state: 'ID' },
  { prefix: '837', state: 'ID' },
  { prefix: '838', state: 'ID' },
  { prefix: '84', state: 'UT' },
  { prefix: '85', state: 'AZ' },
  { prefix: '86', state: 'AZ' },
  { prefix: '87', state: 'NM' },
  { prefix: '88', state: 'NM' },
  { prefix: '889', state: 'NV' },
  { prefix: '89', state: 'NV' },
  { prefix: '90', state: 'CA' },
  { prefix: '91', state: 'CA' },
  { prefix: '92', state: 'CA' },
  { prefix: '93', state: 'CA' },
  { prefix: '94', state: 'CA' },
  { prefix: '95', state: 'CA' },
  { prefix: '96', state: 'CA' },
  { prefix: '967', state: 'HI' },
  { prefix: '968', state: 'HI' },
  { prefix: '969', state: 'GU' },
  { prefix: '97', state: 'OR' },
  { prefix: '98', state: 'WA' },
  { prefix: '99', state: 'WA' },
  { prefix: '995', state: 'AK' },
  { prefix: '996', state: 'AK' },
  { prefix: '997', state: 'AK' },
  { prefix: '998', state: 'AK' },
  { prefix: '999', state: 'AK' },
].sort((a, b) => b.prefix.length - a.prefix.length)

export function stateFromZip(zip: string): string | null {
  const digits = zip.replace(/\D/g, '').slice(0, 5)
  if (digits.length < 3) return null
  for (const { prefix, state } of STATE_BY_PREFIX) {
    if (digits.startsWith(prefix)) return state
  }
  return null
}

export type ParsedZipInput = {
  state: string | null
  zip: string
  raw: string
}

export function parseZipInput(input: string): ParsedZipInput {
  const trimmed = input.trim()
  const match = trimmed.match(/^(?:([A-Za-z]{2})\s+)?(\d{5}(?:-\d{4})?)$/)
  if (!match) return { state: null, zip: '', raw: trimmed }
  const [, explicitState, zip] = match
  const state = explicitState ? explicitState.toUpperCase() : stateFromZip(zip)
  return { state, zip, raw: trimmed }
}

export const ZIP_OR_STATE_ZIP_REGEX = /^(?:[A-Za-z]{2}\s+)?\d{5}(-\d{4})?$/
