import { describe, it, expect, vi, beforeEach } from 'vitest'
import { NextRequest } from 'next/server'
import { POST } from '../route'
import { UserAuthServerManager } from '@/lib/userAuthServer'

vi.mock('@/lib/userAuthServer', () => ({
  UserAuthServerManager: {
    validateUserAccess: vi.fn(),
    generateMyEventsLink: vi.fn(),
  },
}))

describe('/api/user/validate', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('should validate correct email and token', async () => {
    const email = 'test@example.com'
    const token = 'valid-token'

    vi.mocked(UserAuthServerManager.validateUserAccess).mockReturnValue(true)

    const request = new NextRequest('http://localhost/api/user/validate', {
      method: 'POST',
      body: JSON.stringify({ email, token }),
    })

    const response = await POST(request)
    const result = await response.json()

    expect(response.status).toBe(200)
    expect(result).toEqual({
      valid: true,
      email: email,
    })
    expect(UserAuthServerManager.validateUserAccess).toHaveBeenCalledWith(email, token)
  })

  it('should reject invalid email and token', async () => {
    const email = 'test@example.com'
    const token = 'invalid-token'

    vi.mocked(UserAuthServerManager.validateUserAccess).mockReturnValue(false)

    const request = new NextRequest('http://localhost/api/user/validate', {
      method: 'POST',
      body: JSON.stringify({ email, token }),
    })

    const response = await POST(request)
    const result = await response.json()

    expect(response.status).toBe(200)
    expect(result).toEqual({
      valid: false,
      email: null,
    })
    expect(UserAuthServerManager.validateUserAccess).toHaveBeenCalledWith(email, token)
  })

  it('should return 400 for missing email', async () => {
    const request = new NextRequest('http://localhost/api/user/validate', {
      method: 'POST',
      body: JSON.stringify({ token: 'some-token' }),
    })

    const response = await POST(request)
    const result = await response.json()

    expect(response.status).toBe(400)
    expect(result).toEqual({
      error: 'Email and token are required',
    })
    expect(UserAuthServerManager.validateUserAccess).not.toHaveBeenCalled()
  })

  it('should return 400 for missing token', async () => {
    const request = new NextRequest('http://localhost/api/user/validate', {
      method: 'POST',
      body: JSON.stringify({ email: 'test@example.com' }),
    })

    const response = await POST(request)
    const result = await response.json()

    expect(response.status).toBe(400)
    expect(result).toEqual({
      error: 'Email and token are required',
    })
    expect(UserAuthServerManager.validateUserAccess).not.toHaveBeenCalled()
  })

  it('should return 400 for empty request body', async () => {
    const request = new NextRequest('http://localhost/api/user/validate', {
      method: 'POST',
      body: JSON.stringify({}),
    })

    const response = await POST(request)
    const result = await response.json()

    expect(response.status).toBe(400)
    expect(result).toEqual({
      error: 'Email and token are required',
    })
    expect(UserAuthServerManager.validateUserAccess).not.toHaveBeenCalled()
  })

  it('should handle JSON parsing errors', async () => {
    const request = new NextRequest('http://localhost/api/user/validate', {
      method: 'POST',
      body: 'invalid-json',
    })

    const response = await POST(request)

    expect(response.status).toBe(500)
    expect(UserAuthServerManager.validateUserAccess).not.toHaveBeenCalled()
  })

  it('should handle UserAuthServerManager errors', async () => {
    const email = 'test@example.com'
    const token = 'some-token'

    vi.mocked(UserAuthServerManager.validateUserAccess).mockImplementation(() => {
      throw new Error('Validation service error')
    })

    const request = new NextRequest('http://localhost/api/user/validate', {
      method: 'POST',
      body: JSON.stringify({ email, token }),
    })

    const response = await POST(request)
    const result = await response.json()

    expect(response.status).toBe(500)
    expect(result).toEqual({
      error: 'Validation failed',
    })
  })

  it('should validate tokens generated by UserAuthServerManager', async () => {
    const email = 'test@example.com'
    const link = 'http://localhost/my_events?email=test%40example.com&token=valid-token-123'

    vi.mocked(UserAuthServerManager.generateMyEventsLink).mockReturnValue(link)

    const generatedLink = UserAuthServerManager.generateMyEventsLink(email)

    const url = new URL(generatedLink, 'http://localhost')
    const token = url.searchParams.get('token')

    vi.mocked(UserAuthServerManager.validateUserAccess).mockReturnValue(true)

    const request = new NextRequest('http://localhost/api/user/validate', {
      method: 'POST',
      body: JSON.stringify({ email, token }),
    })

    const response = await POST(request)
    const result = await response.json()

    expect(response.status).toBe(200)
    expect(result).toEqual({
      valid: true,
      email: email,
    })
    expect(UserAuthServerManager.validateUserAccess).toHaveBeenCalledWith(email, token)
  })
})
